
private["_filter"];
_filter = [_this,0,0,[0]] call BIS_fnc_param;
//Classname, Custom Display name (use nil for Cfg->DisplayName, price

ctrlSetText[3103,"Clothing Store"];

switch (_filter) do
{
	//Uniforms
	case 0:
	{
		[
		["KI_GucciChecker1",nil,50],
		["KI_GucciCheckerBT1",nil,50],
		["KI_GucciHoriPattern1",nil,50],
		["KI_GucciHoriPatternBT1",nil,50],
		["KI_GucciLogo1",nil,50],
		["KI_GucciLogoBlack1",nil,50],
		["KI_GucciStripe1",nil,50],
		["KI_LVBG1",nil,50],
		["KI_LVBGPat1",nil,50],
		["KI_OvoBT1",nil,50],
		["KI_OvoWT1",nil,50],
		["KI_SupremeBlack1",nil,50],
		["KI_SupremeBlackWT1",nil,50],
		["KI_SupremeStrikeBlack1",nil,50],
		["KI_SupremeStrikeBurgundy1",nil,50],
		["KI_SupremeStrikeWhite1",nil,50],
		["KI_SupremeWhite1",nil,50],
		["KI_SupremeWhiteBT1",nil,50],
		//
		["ALRPJakeRead",nil,50],
		["ALRPCulyerPuggy",nil,50],
		["ALRPHarveyG",nil,50],
		["ALRPDusty",nil,50],
		["ALRPJeff",nil,50],
		["ALRPPopcoin",nil,50],
		["ALRPbeware",nil,50],
		["ALRP911",nil,50],
		["ALRPTrump",nil,50],
		["ALRPRules",nil,50],
		["ALRPRemember",nil,50],
		["ALRPVape",nil,50],
		["ALRPBantu",nil,50],
		["ALRPHarambe",nil,50],
		["alrppugs",nil,50],
		["alrppugsnotdrugs",nil,50],
		["alrpbarney",nil,50],
		["alrpcobra",nil,50],
		["ALRPCulyer",nil,50],
		["alrpcow",nil,50],
		["alrpdrinkdriver",nil,50],
		["alrpfetus",nil,50],
		["alrpfour",nil,50],
		["alrpguilt",nil,50],
		["alrpbond",nil,50],
		["alrpleon",nil,50],
		["alrpllama",nil,50],
		["alrpmoose",nil,50],
		["alrpnandos",nil,50],
		["alrppedo",nil,50],
		["alrppostman",nil,50],
		["alrppringle",nil,50],
		["alrpputin",nil,50],
		["alrpsuit",nil,50],
		["alrpsuperman",nil,50],
		["alrpwithstupid",nil,50],
		///
		["Arabian_dress1",nil,500],
		["Arabian_dress2",nil,500],
		["Arabian_dress4",nil,500],
		//New shit
		["EF_MX1",nil,50],
		["EF_MKJKT",nil,72],
		["EF_MKJKT2",nil,72],
		["EF_M_jkt2",nil,72],
		["EF_M_jkt22",nil,72],
		["EF_M_jkt1",nil,72],
		["EF_M_jkt2_2",nil,72],
		["EF_M_jkt2_22",nil,72],
		["EF_M_jkt1_2",nil,72],
		["EF_M_jkt2_3",nil,72],
		["EF_M_jkt2_32",nil,72],
		["EF_M_jkt1_3",nil,72],
		["EF_M_jkt32_2",nil,72],
		//new bullshittery continues
		["EF_M_jkt2_4",nil,72],
		["EF_M_jkt3",nil,72],
		["EF_M_jkt32",nil,72],
		//
		["EF_HM_LPBPS",nil,84],
		["EF_HM_LPBP",nil,84],
		["EF_HM_LPBR",nil,84],
		["EF_HM_LPBW",nil,84],
		["EF_HM_LPB",nil,84],
		["EF_HM_LPBL",nil,84],
		["EF_HM_LPBPS2",nil,84],
		["EF_HM_LPBP2",nil,84],
		["EF_HM_LPBL2",nil,84],
		//end
		["KAEL_SUITS_BR_F12",nil,175],
		["A3L_Suit_Uniform","Suit",135],
		["KAEL_SUITS_BR_F",nil,135],
		["KAEL_SUITS_BR_F3",nil,135],
		["KAEL_SUITS_BR_F4",nil,135],
		["KAEL_SUITS_BR_F5",nil,135],
		["KAEL_SUITS_BR_F6",nil,135],
		["KAEL_SUITS_BR_F7",nil,135],
		["KAEL_SUITS_BR_F8",nil,135],
		["KAEL_SUITS_BR_F9",nil,135],
		["KAEL_SUITS_BR_F10",nil,135],
		["KAEL_SUITS_BR_F11",nil,135],
		["KAEL_SUITS_BR_F13",nil,135],
		["KAEL_SUITS_BR_F14",nil,135],
		["TRYK_SUITS_BLK_F","Black Suit",135],
		["TRYK_SUITS_BR_F","Brown Suit",135],
		//Female Suits
		["EF_suit_1",nil,135],
		["EF_suit_2",nil,135],
		["EF_suit_3",nil,135],
		["EF_suit_4",nil,135],
		["EF_suit_5",nil,135],
		["EF_suit_6",nil,135],
		//End of female suits
		//FEMALE CLOTHING
		["EF_FEM_3_42",nil,72],
		["EF_FEM_3_3LPBPS",nil,72],
		["EF_FEM_3_3LPBP",nil,72],
		["EF_FEM_3_3LPBR",nil,72],
		["EF_FEM_3_3LPBW",nil,72],
		["EF_FEM_3_3LPB",nil,72],
		["EF_FEM_3_3LPBL",nil,72],
		["EF_FEM_3_3LPBPS2",nil,72],
		["EF_FEM_3_3LPBP2",nil,72],
		["EF_FEM_3_3LPBR2",nil,72],
		["EF_FEM_3_3LPBW2",nil,72],
		["EF_FEM_3_3LPB2",nil,72],
		["EF_FEM_3_3LPBL2",nil,72],
		//
		["EF_FEM_3_75",nil,66],
		["EF_FEM_3_75R",nil,66],
		["EF_FEM_3_76",nil,66],
		["EF_FEM_3_76R",nil,66],
		["EF_FEM_3_73",nil,66],
		["EF_FEM_3_73R",nil,66],
		["EF_FEM_3_74",nil,66],
		["EF_FEM_3_74R",nil,66],
		["EF_FEM_3_7",nil,66],
		["EF_FEM_3_7R",nil,66],
		["EF_FEM_3_72",nil,66],
		["EF_FEM_3_72R",nil,66],
		["EF_FEM_3_5B",nil,66],
		["EF_FEM_3_5BP",nil,66],
		["EF_FEM_3_5VP",nil,66],
		["EF_FEM_3_5RC",nil,66],
		["EF_FEM_3_5W",nil,66],
		["EF_FEM_3_52",nil,66],
		["EF_FEM_3",nil,66],
		["EF_FEM_4A",nil,66],
		["EF_FEM_4A2",nil,66],
		["EF_FEM_4A2_2",nil,66],
		//
		["EF_FEM_4_2LPBPS",nil,72],
		["EF_FEM_4_2LPBP",nil,72],
		["EF_FEM_4_2LPBR",nil,72],
		["EF_FEM_4_2LPBL",nil,72],
		["EF_FEM_4_2LPBPS2",nil,72],
		["EF_FEM_4_2LPBR2",nil,72],
		["EF_FEM_4_2LPBW2",nil,72],
		["EF_FEM_4_2LPB2",nil,72],
		["EF_FEM_4_2LPBL2",nil,72],
		//
		["EF_FEM_4_75",nil,66],
		["EF_FEM_4_76",nil,66],
		["EF_FEM_4_73",nil,66],
		["EF_FEM_4_73R",nil,66],
		["EF_FEM_4_74",nil,66],
		["EF_FEM_4_7",nil,66],
		["EF_FEM_4_72",nil,66],
		//
		["EF_FEM_4_4B",nil,66],
		["EF_FEM_4_4BP",nil,66],
		["EF_FEM_4_4VP",nil,66],
		["EF_FEM_4_4RC",nil,66],
		["EF_FEM_4_4W",nil,66],
		["EF_FEM_5",nil,66],
		["EF_FEM_62",nil,66],
		["EF_FEM_6",nil,66],
		//END OF FEMALE SHIT
		["TRYK_U_B_PCUODHs",nil,250],
		["TRYK_U_B_PCUGHs",nil,250],
		["TRYK_U_B_PCUHs",nil,250],

		["TRYK_U_B_BLOD_T","Black T Green P",50],
		["TRYK_U_B_BLKTANR_CombatUniformTshirt","Black T Tan P II",70],
		["TRYK_U_B_BLTAN_T","Black T Dark Tan P",50],
		["TRYK_U_B_fleece_UCP","Leader",50],
		["TRYK_U_B_ODTANR_CombatUniformTshirt","Green T Tan P",80],
		["TRYK_U_B_PCUGs_OD","Jeans Green Hood",80],
		["TRYK_U_B_PCUGs_gry","Jeans Gray Hood ",80],
		["TRYK_U_B_PCUGs_BLK","Jeans Black Hood",80],
		["TRYK_U_B_C02_Tsirt","Baggy Jeans + Black T",50],
		["TRYK_OVERALL_SAGE_BLKboots_nk","Coveralls Green",40],
		["TRYK_OVERALL_nok_flesh","Coveralls Tan",40],
		["TRYK_U_B_wh_blk_Rollup_CombatUniform","White T Black Cargos",70],
		["TRYK_U_B_wh_tan_Rollup_CombatUniform","White T Tan Cargos",70],
		["TRYK_U_pad_hood_Blk","Black Hood Tan Cargos",10],
		["TRYK_U_denim_hood_blk","Black Hood Jeans II",15],
		["TRYK_U_denim_jersey_blk","Black T & Jeans",10],
		["TRYK_U_denim_jersey_blu","Blue T & Jeans",10],
		["TRYK_U_denim_hood_nc","Green Hood & Jeans",10],
		["TRYK_U_taki_wh","Tan Mid East",10],
		["TRYK_U_taki_BLK","Black Mid East",10],
		["TRYK_U_taki_COY","Brown Mid East ",10],

		["TRYK_U_B_BLK_T_BK","Black Jeans (Black)",50],
		["TRYK_U_B_BLK_T_WH","Black Jeans (White)",50],
		["TRYK_U_B_Denim_T_BK","Grey Jeans (Black)",50],
		["TRYK_U_B_Denim_T_WH","Grey Jeans (White)",50],

		["A3L_Priest_Uniform","Priest Uniform",10],
		["A3L_Character_Uniform","Life Uniform",15],
		["A3L_Dude_Outfit","Dude outfit",200],
		["A3L_Farmer_Outfit","Farmer Outfit",200],
		["A3L_Worker_Outfit","Worker Outfit",200],
		["A3L_SpookyMummy","Mummy",400],
		["skn_u_nbc_opf_yellow","Hazmat Suit",3000]		
		];
	};
	
	//Hats
	case 1:
	{
		[
			["example_HelmetB",nil,100],
			["UR_Bag18",nil,100],
			["UR_Bag13",nil,100],
			["UR_Bag6",nil,100],
			["UR_Bag26",nil,100],
			["UR_Bag8",nil,100],
			["UR_Bag3",nil,100],
			["UR_Bag10",nil,100],
			["UR_Bag2",nil,100],
			["UR_Bag4",nil,100],
			["UR_Bag7",nil,100],
			["UR_Bag17",nil,100],
			["UR_Bag25",nil,100],
			["UR_Bag19",nil,100],
			["UR_Bag20",nil,100],
			["UR_Bag24",nil,100],
			["UR_Bag11",nil,100],
			["UR_Bag16",nil,100],
			["UR_Bag14",nil,100],
			["UR_Brear_Brown",nil,100],
			["UR_Brear_Gray",nil,100],
			["UR_Beerhat_Blue",nil,100],
			["UR_Beerhat_Green2",nil,100],
			["UR_Beerhat_Yellow",nil,100],
			["UR_Buffalo",nil,100],
			["UR_Cat_Gray",nil,100],
			["UR_Cat_Tabby",nil,100],
			["UR_Dino_Brown",nil,100],
			["UR_Dino_Striped",nil,100],
			["UR_Fox",nil,100],
			["UR_Hawk_Brown",nil,100],
			["UR_Hawk_White",nil,100],
			["UR_Hockey_Mask_4_BULLSEYE",nil,100],
			["UR_Hockey_Mask_4_DIRTY",nil,100],
			["UR_Hockey_Mask_4_WOOD",nil,100],
			["UR_Monkey",nil,100],
			["UR_Monkey_DarkBrown",nil,100],
			["UR_Monkey_Grey",nil,100],
			["UR_Monkey_LightBrown",nil,100],
			["UR_Owl",nil,100],
			["UR_Pig",nil,100],
			["UR_Pig_Bloody",nil,100],
			["UR_Skull_Black",nil,100],
			["UR_Skull_Bone",nil,100],
			["UR_Skull_Brown",nil,100],
			["UR_Skull_Grey",nil,100],
			["UR_Wolf",nil,100],
			["UR_Zombie",nil,100],
			["UR_Zombie_Grey",nil,100],
			["BL_eimer_Hat",nil,100],
			["BL_mask_Hat",nil,100],
			["BL_medieval_hat",nil,100],
			["BL_mask2_Hat",nil,100],
			["BL_trump_Hat",nil,100],
			["BL_party_Hat",nil,100],
			["BL_us_Hat",nil,100],
			//New
			["arabian_Hat1",nil,100],
			["arabian_Hat2",nil,100],
			["arabian_Hat3",nil,100],
			["arabian_Hat",nil,100],
			///
			//New
			["H_Construction_basic_black_F",nil,100],
			["H_Construction_earprot_black_F",nil,100],
			["H_Construction_headset_black_F",nil,100],
			["H_Construction_basic_orange_F",nil,100],
			["H_Construction_earprot_orange_F",nil,100],
			["H_Construction_headset_orange_F",nil,100],
			["H_Construction_basic_red_F",nil,100],
			["H_Construction_earprot_red_F",nil,100],
			["H_Construction_headset_red_F",nil,100],
			["H_Construction_basic_white_F",nil,100],
			["H_Construction_earprot_white_F",nil,100],
			["H_Construction_headset_white_F",nil,100],
			["H_Construction_basic_yellow_F",nil,100],
			["H_Construction_earprot_yellow_F",nil,100],
			["H_Construction_headset_yellow_F",nil,100],
			["H_Construction_earprot_yellow_F",nil,100],
			["H_PASGT_basic_blue_press_F",nil,1200],
			////
			["JM_ChickenHead",nil,600],
			["JM_Cow",nil,600],
			["JM_Creeper",nil,600],
			["JM_Pig",nil,600],
			["JM_Slime",nil,600],
			["JM_Spider",nil,600],
			["JM_Clone",nil,600],
			["JM_Deadmau5",nil,600],
			["JM_Football",nil,600],
			["JM_KFC",nil,600],
			["JM_Party",nil,600],
			["JM_Wizard",nil,600],
			//NEW
			["JM_Yoshi",nil,600],
			["JM_Luigi",nil,600],
			["JM_Mario",nil,600],
			["JM_Heavy",nil,600],
			["JM_Doggo1",nil,600],
			["JM_Doggo3",nil,600],
			["JM_Doggo4",nil,600],
			["JM_Doggo6",nil,600],
			["JM_Doggo5",nil,600],
			["JM_Doggo",nil,600],
			["JM_Doggo2",nil,600],
			["JM_Goat",nil,600],
			["JM_sheep",nil,600],
			["JM_Chicken",nil,600],
			["JM_Spiderman",nil,600],
			["JM_wig1",nil,600],
			["JM_Chain_2",nil,600],
			["JM_Vape_Bandana",nil,600],
			//end of new memes
			["Masque_Bush",nil,100],
			["Masque_Dallas",nil,100],
			["Masque_Clover",nil,100],
			["Masque_Clinton",nil,100],
			["Masque_Lincoln",nil,100],
			["Masque_Lion",nil,100],
			["Masque_Macrilleuse",nil,100],
			["Masque_Mark",nil,100],
			["Masque_Metalhead",nil,100],
			["Masque_forceAlpha",nil,100],
			["Masque_Incendiaire",nil,100],
			["Masque_Hockey",nil,100],
			["Masque_Mempo",nil,100],
			["Masque_Hockey",nil,100],
			["Masque_GdG",nil,100],
			["Masque_Aubrey",nil,100],
			["Masque_Chuck",nil,100],
			["Masque_Alien1",nil,100],
			["ALE_H_NewEra_Monster",nil,150],
			["ALE_H_NewEra_Rouge",nil,150],
			["ALE_H_NewEra_Superman",nil,150],
			["ALE_H_NewEra_Cyan",nil,150],
			["ALE_H_NewEra_Black",nil,150],
			["ALE_H_NewEra_Lakers",nil,150],
			["ALE_H_NewEra_Redsox",nil,150],
			["ALE_H_Calot",nil,120],
			["ALE_H_Cowboy_White",nil,120],
			["ALE_H_Cowboy_Black",nil,120],
			["ALE_H_Cowboy_Brown",nil,120],
			["Campaign_Hat_Puggy",nil,100],
            ["kio_vfv_mask","Anon", 10],
            ["Kio_Capital_Hat","Top Hat w/Monacle", 10],
            ["a3l_hardhat","Hard Hat", 200],
            ["Kio_Afro_Hat","Brown Afro", 200],
            ["H_Beret_blk","Black Beret", 200],
            ["H_Booniehat_khk",nil, 40],
            ["H_Booniehat_oli",nil, 40],
            ["H_Booniehat_tan",nil, 40],
			["TRYK_H_Booniehat_CC",nil, 40],
            ["TRYK_H_Booniehat_AOR2",nil, 40],
            ["TRYK_H_Booniehat_3CD",nil, 40],
			["TRYK_H_Booniehat_MARPAT_WOOD",nil, 40],
            ["TRYK_H_Booniehat_JSDF",nil, 40],
            ["TRYK_H_Booniehat_WOOD",nil, 40],
            ["Kio_No1_Hat",nil, 200],
			["Masque_archNemesis",nil, 2000],
			["Masque_Fish",nil, 100],
			["Masque_Optimiste",nil, 9000],
			["Masque_Religieuse",nil, 500],
			["Masque_Smiley",nil, 3000],
			["Masque_speedRunner",nil, 3000],
			["Masque_Unic",nil, 3000],
		    ["Kio_Pirate_Hat","Pirate Hat", 10],
            ["Kio_Spinning_Hat","Spinning Hat", 200],
            ["Kio_Hat","Cute Warm Hat", 200],
            ["TRYK_H_Bandana_H","Ninja Bandana",10],
            ["TRYK_H_Bandana_wig","Ninja Bandana II",200],
            ["TRYK_H_EARMUFF","Ear Protectors",200],
            ["TRYK_H_headsetcap_blk","Black Hat",10],
            ["TRYK_H_headsetcap","White Hat",10],
            ["TRYK_H_pakol2","Mid East Hat",10],
            ["TRYK_R_CAP_BLK","Reverse Black",10],
            ["TRYK_R_CAP_TAN","Reverse White",10],
            ["TRYK_H_wig","Real Hair Wig",200],
            ["TRYK_H_woolhat","Slick Beanie",400],
			["A3L_Legoman","Lego Helmet",500],
			["A3L_soa_helmet","Biker Helmet",40],	
			["A3L_gangster_hat","Gangster Mask",10],
			["A3L_Mask","Mask",10],				
			["A3L_longhairblack","Long Hair Black",120],
			["A3L_longhairblond","Long Hair Blond",120],
			["A3L_longhairbrown","Long Hair Brown",120],
			["A3L_Crown","Crown",120],
			["cowboyhat","Cowboyhat",120],
			["A3L_mexicanhat","Mexican Hat",120],
			["A3L_Sombrero","Sombrero",120],
			["turban","Turban",120],
			["A3L_russianhat","Russianhat",120]

		];
	};
	
	//Glasses
	case 2:
	{
		[
			//beards
			["SFG_Tac_smallBeardB",nil,25],
			["SFG_Tac_smallBeardD",nil,25],
			["SFG_Tac_smallBeardG",nil,25],
			["SFG_Tac_smallBeardO",nil,25],
			["SFG_Tac_BeardB",nil,25],
			["SFG_Tac_BeardD",nil,25],
			["SFG_Tac_BeardG",nil,25],
			["SFG_Tac_BeardO",nil,25],
			["SFG_Tac_chinlessbB",nil,25],
			["SFG_Tac_chinlessbD",nil,25],
			["SFG_Tac_chinlessbG",nil,25],
			["SFG_Tac_chinlessbO",nil,25],
			["SFG_Tac_moustacheB",nil,25],
			["SFG_Tac_moustacheD",nil,25],
			["SFG_Tac_moustacheG",nil,25],
			["SFG_Tac_moustacheO",nil,25],
			["SFG_Tac_ChopsB",nil,25],
			["SFG_Tac_ChopsD",nil,25],
			["SFG_Tac_ChopsG",nil,25],
			["SFG_Tac_ChopsO",nil,25],
			["G_Shades_Black",nil,25],
			["G_Shades_Blue",nil,20],
			["G_Sport_Blackred",nil,20],
			["G_Sport_Checkered",nil,20],
			["G_Sport_Blackyellow",nil,20],
			["G_Sport_BlackWhite",nil,20],
			["G_Aviator",nil,10],
			["G_Lady_Mirror",nil,15],
			["G_Lady_Dark",nil,15],
			["G_Lady_Blue",nil,15],
			["G_Lowprofile",nil,30],
			["G_Combat",nil,55]
		];
	};
	
	//Vest
	case 3:
	{
		[
		["V_Press_F",nil,250],
		//
		["V_Safety_blue_F",nil,155],
		["V_Safety_orange_F",nil,155],
		["V_Safety_yellow_F",nil,155],
		///
		["k_cut_1",nil,255],
		["k_cut_2",nil,255],
		["k_cut_3",nil,255],
		["k_cut_4",nil,255],
		["k_cut_5",nil,255],
		["k_cut_6",nil,255],
		["k_cut_7",nil,255],
		["k_cut_8",nil,255],
		["k_cut_9",nil,255],
		["k_cut_10",nil,255],
		["k_cut_11",nil,255]
		];
	};
	
	//Backpacks
	case 4:
	{
		[
            
			["tf_anprc155",nil,500],
			["B_AssaultPack_cbr",nil,250],
			["B_AssaultPack_rgr",nil,250],
			["B_AssaultPack_khk",nil,250],
			["B_AssaultPack_sgg",nil,250],
			["B_AssaultPack_blk",nil,250],
			["B_TacticalPack_oli",nil,35],
			["B_Bergen_sgg",nil,450],
			["B_FieldPack_oli",nil,450],
			["B_FieldPack_cbr",nil,450],
			["B_FieldPack_khk",nil,450],
			["B_Carryall_oli",nil,500],
			["B_Carryall_khk",nil,500],
			["kaelmonty",nil,550],	
			["kaelmonty2",nil,550],
			["kaelmario",nil,550],	
			["kaelsuits",nil,550],	
			["koilbatman_1",nil,550],	
			["koilbender_1",nil,550],	
			["koilbender_2",nil,550],	
			["koilclint_1",nil,550],	
			["koileminem_1",nil,550],	
			["koilgraf_1",nil,550],	
			["koilgraf_2",nil,550],	
			["koilgraf_3",nil,550],	
			["koilhulk_1",nil,550],	
			["koiljoker_1",nil,550],	
			["koilpumpkin_1",nil,550],	
			["koilsparta_1",nil,550],	
			["koilsponge_1",nil,550],	
			["koilturtles_1",nil,550],	
			["koilkatie",nil,550],
			["koilpanda",nil,550],
			["koilaiden",nil,550],
			["koileagle",nil,550],
			["koilspecktators",nil,550],
			["koildarth",nil,550],
			["koilgucci",nil,550],
			["koilsmashing",nil,550],
			["koilgoonsquad",nil,550],
			["koilcat",nil,550],
			["koilbp_19",nil,550],	
			["koilbp_21",nil,550],	
			["koilbp_22",nil,550],
			["koilbp_1",nil,550],	
			["koilbp_2",nil,550],	
			["koilbp_3",nil,550],	
			["koilbp_4",nil,550],	
			["koilbp_5",nil,550],	
			["koilbp_6",nil,550],	
			["koilbp_7",nil,550],	
			["koilbp_8",nil,550],	
			["koilbp_9",nil,550],	
			["koilbp_10",nil,550],	
			["koilbp_11",nil,550],	
			["koilbp_12",nil,550],	
			["koilbp_13",nil,550],	
			["koilbp_14",nil,550],	
			["koilbp_15",nil,550],	
			["koilbp_16",nil,550],	
			["koilbp_17",nil,550],	
			["koilbp_18",nil,550],
			//CIV UAVs
			["sab_cuav_bp_blue",nil,45000],
			["sab_cuav_bp_green",nil,45000],
			["sab_cuav_bp_orange",nil,45000],
			["sab_cuav_bp_red",nil,45000],
			["sab_cuav_bp_violet",nil,45000]
		];
	};
};
