
private["_filter"];
_filter = [_this,0,0,[0]] call BIS_fnc_param;
//Classname, Custom Display name (use nil for Cfg->DisplayName, price

//Shop Title Name
ctrlSetText[3103,"Cobra's Clothing Store"];

switch (_filter) do
{
	//Uniforms
	case 0:
	{
		[
		["U_FRITH_RUIN_sdr_fabdpm",nil,55],
			["U_FRITH_RUIN_coffgrn",nil,55],
			["U_FRITH_RUIN_cofftan",nil,55],
			["U_FRITH_RUIN_sdr_fabdpm",nil,55],
			["U_FRITH_RUIN_sdr_fabmtp",nil,55],
			["U_FRITH_RUIN_sdr_fabrus",nil,55],
			["U_FRITH_RUIN_SDR_Tshirt_oli_bet",nil,55],
			///////////////////////////////////////////////
			["U_FRITH_RUIN_TSH_cry",nil,55],
			["U_FRITH_RUIN_TSH_wht_zap",nil,55],
			["U_FRITH_RUIN_TSH_wht_stk",nil,55],
			["U_FRITH_RUIN_TSH_wht_fpk",nil,55],
			["U_FRITH_RUIN_WKR_dark",nil,55],
			["U_FRITH_RUIN_SDR_snip_hawk",nil,125],
			["U_FRITH_RUIN_SDR_snip_crow",nil,600],
			/////////////////////////////////
			["U_I_FullGhillie_lsh",nil,600],
			["U_O_OfficerUniform_ocamo",nil,150],
			["TRYK_U_B_ARO1_BLK_CombatUniform",nil,150],
			["TRYK_U_B_AOR2_BLK_R_CombatUniform",nil,150],
			["TRYK_U_B_Snowt",nil,150],
			["TRYK_U_B_AOR2_BLK_R_CombatUniform",nil,150],
			["TRYK_U_B_AOR2_GRY_CombatUniform",nil,150],
			["TRYK_U_B_AOR2_GRY_R_CombatUniform",nil,150],
			["TRYK_U_B_AOR2_OD_R_CombatUniform",nil,150],
			["TRYK_U_B_BLKBLK_R_CombatUniform",nil,150],
			["TRYK_U_B_BLKTANR_CombatUniformTshirt",nil,150],
			["TRYK_U_B_fleece_UCP",nil,150],
			["TRYK_U_B_fleece",nil,150],
			["TRYK_U_B_BLK_tan_Rollup_CombatUniform",nil,150],
			["TRYK_U_B_PCUHsW3",nil,150],
			//FEMALE VARIANTS
			["EF_FEM_2U",nil,150],
			["EF_FEM_2BK",nil,150],
		["JM_7111",nil,50],
		["JM_Amazon1",nil,50],
		["JM_Bernie1",nil,50],
		["JM_Bender1",nil,50],
		["JM_Gatorade1",nil,50],
		["JM_Hilary1",nil,50],
		["JM_Jelly1",nil,50],
		["JM_Jurassic1",nil,50],
		["JM_Lad1",nil,50],
		["JM_Minion1",nil,50],
		["JM_Nasa1",nil,50],
		["JM_netflix1",nil,50],
		["JM_Egg1",nil,50],
		["JM_PB1",nil,50],
		["JM_Phut1",nil,50],
		["JM_pumba1",nil,50],
		["JM_Siege1",nil,50],
		["JM_sloth1",nil,50],
		["JM_Target1",nil,50],
		["JM_Trump1",nil,50],
		["JM_Vape1",nil,50],
		["JM_Walmart1",nil,50],
		///
		["ALRPJakeRead",nil,50],
		["ALRPCulyerPuggy",nil,50],
		["ALRPHarveyG",nil,50],
		["ALRPDusty",nil,50],
		["ALRPJeff",nil,50],
		["ALRPPopcoin",nil,50],
		["ALRPbeware",nil,50],
		["ALRP911",nil,50],
		["ALRPTrump",nil,50],
		["ALRPRules",nil,50],
		["ALRPRemember",nil,50],
		["ALRPVape",nil,50],
		["ALRPBantu",nil,50],
		["ALRPHarambe",nil,50],
		["alrppugs",nil,50],
		["alrppugsnotdrugs",nil,50],
		["alrpbarney",nil,50],
		["alrpcobra",nil,50],
		["ALRPCulyer",nil,50],
		["alrpcow",nil,50],
		["alrpdrinkdriver",nil,50],
		["alrpfetus",nil,50],
		["alrpfour",nil,50],
		["alrpguilt",nil,50],
		["alrpbond",nil,50],
		["alrpleon",nil,50],
		["alrpllama",nil,50],
		["alrpmoose",nil,50],
		["alrpnandos",nil,50],
		["alrppedo",nil,50],
		["alrppostman",nil,50],
		["alrppringle",nil,50],
		["alrpputin",nil,50],
		["alrpsuit",nil,50],
		["alrpsuperman",nil,50],
		["alrpwithstupid",nil,50],
		//New shit
		["EF_MX1",nil,50],
		["EF_MKJKT",nil,72],
		["EF_MKJKT2",nil,72],
		["EF_M_jkt2",nil,72],
		["EF_M_jkt22",nil,72],
		["EF_M_jkt1",nil,72],
		["EF_M_jkt2_2",nil,72],
		["EF_M_jkt2_22",nil,72],
		["EF_M_jkt1_2",nil,72],
		["EF_M_jkt2_3",nil,72],
		["EF_M_jkt2_32",nil,72],
		["EF_M_jkt1_3",nil,72],
		["EF_M_jkt32_2",nil,72],
		//new bullshittery continues
		["EF_M_jkt2_4",nil,72],
		["EF_M_jkt3",nil,72],
		["EF_M_jkt32",nil,72],
		//
		["EF_HM_LPBPS",nil,84],
		["EF_HM_LPBP",nil,84],
		["EF_HM_LPBR",nil,84],
		["EF_HM_LPBW",nil,84],
		["EF_HM_LPB",nil,84],
		["EF_HM_LPBL",nil,84],
		["EF_HM_LPBPS2",nil,84],
		["EF_HM_LPBP2",nil,84],
		["EF_HM_LPBL2",nil,84],
		//end
		["KAEL_SUITS_BR_F12",nil,175],
		["A3L_Suit_Uniform","Suit",135],
		["KAEL_SUITS_BR_F",nil,135],
		["KAEL_SUITS_BR_F3",nil,135],
		["KAEL_SUITS_BR_F4",nil,135],
		["KAEL_SUITS_BR_F5",nil,135],
		["KAEL_SUITS_BR_F6",nil,135],
		["KAEL_SUITS_BR_F7",nil,135],
		["KAEL_SUITS_BR_F8",nil,135],
		["KAEL_SUITS_BR_F9",nil,135],
		["KAEL_SUITS_BR_F10",nil,135],
		["KAEL_SUITS_BR_F11",nil,135],
		["KAEL_SUITS_BR_F13",nil,135],
		["KAEL_SUITS_BR_F14",nil,135],
		["TRYK_SUITS_BLK_F","Black Suit",135],
		["TRYK_SUITS_BR_F","Brown Suit",135],
		//Female Suits
		["EF_suit_1",nil,135],
		["EF_suit_2",nil,135],
		["EF_suit_3",nil,135],
		["EF_suit_4",nil,135],
		["EF_suit_5",nil,135],
		["EF_suit_6",nil,135],
		//End of female suits
		//FEMALE CLOTHING
		["EF_FEM_3_42",nil,72],
		["EF_FEM_3_3LPBPS",nil,72],
		["EF_FEM_3_3LPBP",nil,72],
		["EF_FEM_3_3LPBR",nil,72],
		["EF_FEM_3_3LPBW",nil,72],
		["EF_FEM_3_3LPB",nil,72],
		["EF_FEM_3_3LPBL",nil,72],
		["EF_FEM_3_3LPBPS2",nil,72],
		["EF_FEM_3_3LPBP2",nil,72],
		["EF_FEM_3_3LPBR2",nil,72],
		["EF_FEM_3_3LPBW2",nil,72],
		["EF_FEM_3_3LPB2",nil,72],
		["EF_FEM_3_3LPBL2",nil,72],
		//
		["EF_FEM_3_75",nil,66],
		["EF_FEM_3_75R",nil,66],
		["EF_FEM_3_76",nil,66],
		["EF_FEM_3_76R",nil,66],
		["EF_FEM_3_73",nil,66],
		["EF_FEM_3_73R",nil,66],
		["EF_FEM_3_74",nil,66],
		["EF_FEM_3_74R",nil,66],
		["EF_FEM_3_7",nil,66],
		["EF_FEM_3_7R",nil,66],
		["EF_FEM_3_72",nil,66],
		["EF_FEM_3_72R",nil,66],
		["EF_FEM_3_5B",nil,66],
		["EF_FEM_3_5BP",nil,66],
		["EF_FEM_3_5VP",nil,66],
		["EF_FEM_3_5RC",nil,66],
		["EF_FEM_3_5W",nil,66],
		["EF_FEM_3_52",nil,66],
		["EF_FEM_3",nil,66],
		["EF_FEM_4A",nil,66],
		["EF_FEM_4A2",nil,66],
		["EF_FEM_4A2_2",nil,66],
		//
		["EF_FEM_4_2LPBPS",nil,72],
		["EF_FEM_4_2LPBP",nil,72],
		["EF_FEM_4_2LPBR",nil,72],
		["EF_FEM_4_2LPBL",nil,72],
		["EF_FEM_4_2LPBPS2",nil,72],
		["EF_FEM_4_2LPBR2",nil,72],
		["EF_FEM_4_2LPBW2",nil,72],
		["EF_FEM_4_2LPB2",nil,72],
		["EF_FEM_4_2LPBL2",nil,72],
		//
		["EF_FEM_4_75",nil,66],
		["EF_FEM_4_76",nil,66],
		["EF_FEM_4_73",nil,66],
		["EF_FEM_4_73R",nil,66],
		["EF_FEM_4_74",nil,66],
		["EF_FEM_4_7",nil,66],
		["EF_FEM_4_72",nil,66],
		//
		["EF_FEM_4_4B",nil,66],
		["EF_FEM_4_4BP",nil,66],
		["EF_FEM_4_4VP",nil,66],
		["EF_FEM_4_4RC",nil,66],
		["EF_FEM_4_4W",nil,66],
		["EF_FEM_5",nil,66],
		["EF_FEM_62",nil,66],
		["EF_FEM_6",nil,66],
		//END OF FEMALE SHIT
		["TRYK_U_B_PCUODHs",nil,25],
		["TRYK_U_B_PCUGHs",nil,25],
		["TRYK_U_B_PCUHs",nil,25],

		["TRYK_U_B_BLOD_T","Black T Green P",50],
		["TRYK_U_B_BLKTANR_CombatUniformTshirt","Black T Tan P II",70],
		["TRYK_U_B_BLTAN_T","Black T Dark Tan P",50],
		["TRYK_U_B_fleece_UCP","Leader",50],
		["TRYK_U_B_ODTANR_CombatUniformTshirt","Green T Tan P",80],
		["TRYK_U_B_PCUGs_OD","Jeans Green Hood",80],
		["TRYK_U_B_PCUGs_gry","Jeans Gray Hood ",80],
		["TRYK_U_B_PCUGs_BLK","Jeans Black Hood",80],
		["TRYK_U_B_C02_Tsirt","Baggy Jeans + Black T",50],
		["TRYK_OVERALL_SAGE_BLKboots_nk","Coveralls Green",40],
		["TRYK_OVERALL_nok_flesh","Coveralls Tan",40],
		["TRYK_U_B_wh_blk_Rollup_CombatUniform","White T Black Cargos",70],
		["TRYK_U_B_wh_tan_Rollup_CombatUniform","White T Tan Cargos",70],
		["TRYK_U_pad_hood_Blk","Black Hood Tan Cargos",10],
		["TRYK_U_denim_hood_blk","Black Hood Jeans II",15],
		["TRYK_U_denim_jersey_blk","Black T & Jeans",10],
		["TRYK_U_denim_jersey_blu","Blue T & Jeans",10],
		["TRYK_U_denim_hood_nc","Green Hood & Jeans",10],
		["TRYK_U_taki_wh","Tan Mid East",10],
		["TRYK_U_taki_BLK","Black Mid East",10],
		["TRYK_U_taki_COY","Brown Mid East ",10],

		["TRYK_U_B_BLK_T_BK","Black Jeans (Black)",50],
		["TRYK_U_B_BLK_T_WH","Black Jeans (White)",50],
		["TRYK_U_B_Denim_T_BK","Grey Jeans (Black)",50],
		["TRYK_U_B_Denim_T_WH","Grey Jeans (White)",50],
//koil added

		["A3L_Priest_Uniform","Priest Uniform",10],
		["A3L_Character_Uniform","Life Uniform",15],
		["A3L_Dude_Outfit","Dude outfit",200],
		["A3L_Farmer_Outfit","Farmer Outfit",200],
		["A3L_Worker_Outfit","Worker Outfit",200],
		["A3L_SpookyMummy","Mummy",400],
		["U_C_Scientist","Hazmat Suit",300]		
		];
	};
	
	//Hats
	case 1:
	{
		[
			["FRITH_ruin_modhat_fabdpm",nil,135],
			["FRITH_ruin_modhat_fabaaf",nil,135],
			["FRITH_ruin_modhat_fabdes",nil,135],
			["FRITH_ruin_modhat_fabflw",nil,135],
			["FRITH_ruin_modhat_fabrus",nil,135],
			["FRITH_ruin_modhat_mettan",nil,135],
			/////////////////////
			["H_MilCap_gry",nil,65],
			["H_MilCap_blue",nil,65],
			["H_MilCap_dgtl",nil,65],
			["TRYK_H_Booniehat_AOR2",nil,35],
			["TRYK_H_Booniehat_MARPAT_WOOD",nil,35],
			["TRYK_H_Booniehat_AOR1",nil,35],
			["TRYK_H_Booniehat_JSDF",nil,35],
			["H_Bandanna_camo",nil,65],
			["H_Shemag_olive",nil,65],
			["H_ShemagOpen_tan",nil,65],
			["H_ShemagOpen_khk",nil,65],
			["H_Shemag_olive_hs",nil,65],
			["jokermask","Joker Mask",55],
			["TRYK_Kio_Balaclava","Ghost Balaclava",15],
			["TRYK_H_Bandana_wig",nil,85],
			["TRYK_H_Bandana_wig_g",nil,85],
			["TRYK_Kio_Balaclava",nil,85],
			["kio_skl_msk","Black Skull Mask",52],
			["kio_skl_msk_grn","Green Skull Mask",52],
			["kio_skl_msk_red","Red Skull Mask",52],
			["JM_ChickenHead",nil,600],
			["JM_SteveHead",nil,600],
			["JM_Zombie",nil,600],
			["JM_Cow",nil,600],
			["JM_Creeper",nil,600],
			["JM_Pig",nil,600],
			["JM_Slime",nil,600],
			["JM_Spider",nil,600],
			["JM_Clone",nil,600],
			["JM_Deadmau5",nil,600],
			["JM_Football",nil,600],
			["JM_KFC",nil,600],
			["JM_Party",nil,600],
			["JM_Wizard",nil,600],
			//NEW
			["JM_Yoshi",nil,600],
			["JM_Luigi",nil,600],
			["JM_Mario",nil,600],
			["JM_Heavy",nil,600],
			
			["JM_Doggo1",nil,600],
			["JM_Doggo3",nil,600],
			["JM_Doggo4",nil,600],
			["JM_Doggo6",nil,600],
			["JM_Doggo5",nil,600],
			["JM_Doggo",nil,600],
			["JM_Doggo2",nil,600],
			["JM_Goat",nil,600],
			["JM_sheep",nil,600],
			["JM_Chicken",nil,600],
			["JM_Spiderman",nil,600],
			["JM_wig1",nil,600],
			["JM_Chain_2",nil,600],
			["JM_Vape_Bandana",nil,600],
			//end of new memes
			["Masque_Bush",nil,100],
			["Masque_Dallas",nil,100],
			["Masque_Clover",nil,100],
			["Masque_Clinton",nil,100],
			["Masque_Lincoln",nil,100],
			["Masque_Lion",nil,100],
			["Masque_Macrilleuse",nil,100],
			["Masque_Mark",nil,100],
			["Masque_Metalhead",nil,100],
			["Masque_forceAlpha",nil,100],
			["Masque_Incendiaire",nil,100],
			["Masque_Hockey",nil,100],
			["Masque_Mempo",nil,100],
			["Masque_Hockey",nil,100],
			["Masque_GdG",nil,100],
			["Masque_Aubrey",nil,100],
			["Masque_Chuck",nil,100],
			["Masque_Alien1",nil,100],
			["ALE_H_NewEra_Monster",nil,150],
			["ALE_H_NewEra_Rouge",nil,150],
			["ALE_H_NewEra_Superman",nil,150],
			["ALE_H_NewEra_Cyan",nil,150],
			["ALE_H_NewEra_Black",nil,150],
			["ALE_H_NewEra_Lakers",nil,150],
			["ALE_H_NewEra_Redsox",nil,150],
			["ALE_H_Calot",nil,120],
			["ALE_H_Cowboy_White",nil,120],
			["ALE_H_Cowboy_Black",nil,120],
			["ALE_H_Cowboy_Brown",nil,120],
			["Campaign_Hat_Puggy",nil,100],
            ["kio_vfv_mask","Anon", 10],
            ["Kio_Capital_Hat","Top Hat w/Monacle", 10],
            ["a3l_hardhat","Hard Hat", 200],
            ["Kio_Afro_Hat","Brown Afro", 200],
            ["H_Beret_blk","Black Beret", 200],
            ["H_Booniehat_khk",nil, 40],
            ["H_Booniehat_oli",nil, 40],
            ["H_Booniehat_tan",nil, 40],
			["TRYK_H_Booniehat_CC",nil, 40],
            ["TRYK_H_Booniehat_AOR2",nil, 40],
            ["TRYK_H_Booniehat_3CD",nil, 40],
			["TRYK_H_Booniehat_MARPAT_WOOD",nil, 40],
            ["TRYK_H_Booniehat_JSDF",nil, 40],
            ["TRYK_H_Booniehat_WOOD",nil, 40],
            ["Kio_No1_Hat",nil, 200],
			["Masque_archNemesis",nil, 200],
			["Masque_Fish",nil, 100],
			["Masque_Optimiste",nil, 9000],
			["Masque_Religieuse",nil, 50],
			["Masque_Smiley",nil, 300],
			["Masque_speedRunner",nil, 300],
			["Masque_Unic",nil, 300],
		    ["Kio_Pirate_Hat","Pirate Hat", 10],
            ["Kio_Spinning_Hat","Spinning Hat", 200],
            ["Kio_Hat","Cute Warm Hat", 200],
            ["TRYK_H_Bandana_H","Ninja Bandana",10],
            ["TRYK_H_Bandana_wig","Ninja Bandana II",200],
            ["TRYK_H_EARMUFF","Ear Protectors",200],
            ["TRYK_H_headsetcap_blk","Black Hat",10],
            ["TRYK_H_headsetcap","White Hat",10],
            ["TRYK_H_pakol2","Mid East Hat",10],
            ["TRYK_R_CAP_BLK","Reverse Black",10],
            ["TRYK_R_CAP_TAN","Reverse White",10],
            ["TRYK_H_wig","Real Hair Wig",200],
            ["TRYK_H_woolhat","Slick Beanie",400],
			["A3L_Legoman","Lego Helmet",50],
			["A3L_soa_helmet","Biker Helmet",40],	
			["A3L_gangster_hat","Gangster Mask",10],
			["A3L_Mask","Mask",10],				
			["A3L_longhairblack","Long Hair Black",120],
			["A3L_longhairblond","Long Hair Blond",120],
			["A3L_longhairbrown","Long Hair Brown",120],
			["A3L_Crown","Crown",120],
			["cowboyhat","Cowboyhat",120],
			["A3L_mexicanhat","Mexican Hat",120],
			["A3L_Sombrero","Sombrero",120],
			["turban","Turban",120],
			["A3L_russianhat","Russianhat",120]

		];
	};
	
	//Glasses
	case 2:
	{
		[
			//beards
			["SFG_Tac_smallBeardB",nil,25],
			["SFG_Tac_smallBeardD",nil,25],
			["SFG_Tac_smallBeardG",nil,25],
			["SFG_Tac_smallBeardO",nil,25],
			["SFG_Tac_BeardB",nil,25],
			["SFG_Tac_BeardD",nil,25],
			["SFG_Tac_BeardG",nil,25],
			["SFG_Tac_BeardO",nil,25],
			["SFG_Tac_chinlessbB",nil,25],
			["SFG_Tac_chinlessbD",nil,25],
			["SFG_Tac_chinlessbG",nil,25],
			["SFG_Tac_chinlessbO",nil,25],
			["SFG_Tac_moustacheB",nil,25],
			["SFG_Tac_moustacheD",nil,25],
			["SFG_Tac_moustacheG",nil,25],
			["SFG_Tac_moustacheO",nil,25],
			["SFG_Tac_ChopsB",nil,25],
			["SFG_Tac_ChopsD",nil,25],
			["SFG_Tac_ChopsG",nil,25],
			["SFG_Tac_ChopsO",nil,25],
			["G_Shades_Black",nil,25],
			["G_Shades_Blue",nil,20],
			["G_Sport_Blackred",nil,20],
			["G_Sport_Checkered",nil,20],
			["G_Sport_Blackyellow",nil,20],
			["G_Sport_BlackWhite",nil,20],
			["G_Aviator",nil,10],
			["G_Lady_Mirror",nil,15],
			["G_Lady_Dark",nil,15],
			["G_Lady_Blue",nil,15],
			["G_Lowprofile",nil,30],
			["G_Combat",nil,55],
			["A3L_Balaclava",nil,133]
		];
	};
	
	//Vest
	case 3:
	{
		[
		["SWAT_VEST_NCA","NCA Vest",25],
		["SWAT_VEST_NCAAlt","Alternative NCA Vest",25],
		["V_Press_F",nil,25],
		["k_cut_1",nil,25],
		["k_cut_2",nil,25],
		["k_cut_3",nil,25],
		["k_cut_4",nil,25],
		["k_cut_5",nil,25],
		["k_cut_6",nil,25],
		["k_cut_7",nil,25],
		["k_cut_8",nil,25],
		["k_cut_9",nil,25],
		["k_cut_10",nil,25],
		["k_cut_11",nil,25],
		["ALRP_Alfie",nil,200],
			["ALRP_Pugs",nil,200],
			////////
			["FRITH_ruin_vestia_lite_grn",nil,250],
			["FRITH_ruin_vestia_lite_tar",nil,250],
			["FRITH_ruin_vestia_lite_ltr",nil,250],
			["FRITH_ruin_vestia_lite_nja",nil,250],
			["FRITH_ruin_vestia_ghm",nil,450],
			["FRITH_ruin_vestia_grn",nil,450],
			["FRITH_ruin_vestia_ltr",nil,450],
			["FRITH_ruin_vestia_nja",nil,450],
			//////////////////////////
			["TAC_PBDFG2_B_1",nil,180],
			["TAC_PBDFG2_CY_1",nil,180],
			["TAC_PBDFG2_RG_1",nil,180],
			["TAC_PBDFG2CPL_BK",nil,260],
			["TAC_Punisher_Vest_BK",nil,280],
			["TAC_V_tacv1M_BK",nil,150],
			["TAC_HGB_B",nil,500],
			["TAC_HGB_Khaki",nil,500],
			["TAC_HGB_OD",nil,500],
			["V_PlateCarrierInd_PMC_blk",nil,180],
			["V_TacVest_khk",nil,550],
			["V_TacVest_oli",nil,550],
			["V_TacVest_brn",nil,550],
			["V_BandollierB_cbr",nil,450],
			["V_BandollierB_rgr",nil,450],
			["V_BandollierB_khk",nil,450],
			["V_BandollierB_oli",nil,450],
			["V_HarnessO_brn",nil,780],
			["V_HarnessO_gry",nil,780]
		];
	};
	
	//Backpacks
	case 4:
	{
		[
			["B_AssaultPack_cbr",nil,250],
			["B_FieldPack_ocamo",nil,300],
			["B_TacticalPack_oli","Olive Bergen",350],
			["B_Bergen_sgg","Sage Bergen",450],
			["B_Carryall_oli","Olive Carryall",500],
			["B_Carryall_khk","Khaki Carryall",500],
			//Camo Packs
			["B_AssaultPack_mcamo","MTP Assault Pack",400],
			["TRYK_B_AssaultPack_MARPAT_Wood","MARPAT Assault Pack",550],
			["TRYK_B_AssaultPack_Type2camo","Jungle Assault Pack",550],
			["TRYK_B_Kitbag_Base_JSDF","Jungle Kitbag",550],
			["B_Kitbag_mcamo","MTP Kitbag",550],
			//Belts
			["TRYK_B_Belt_AOR2",nil,300],
			["TRYK_B_Belt_CYT",nil,300],
			["TRYK_B_Belt_GR",nil,300],
			["tf_anprc155",nil,50],
			["B_AssaultPack_cbr",nil,25],
			["B_AssaultPack_rgr",nil,25],
			["B_AssaultPack_khk",nil,25],
			["B_AssaultPack_sgg",nil,25],
			["B_AssaultPack_blk",nil,25],
			["B_TacticalPack_oli",nil,35],
			["B_Bergen_sgg",nil,45],
			["B_FieldPack_oli",nil,45],
			["B_FieldPack_cbr",nil,45],
			["B_FieldPack_khk",nil,45],
			["B_Carryall_oli",nil,50],
			["B_Carryall_khk",nil,50],
			["kaelmonty",nil,55],	
			["kaelmonty2",nil,55],
			["kaelmario",nil,55],	
			["kaelsuits",nil,55],	
			["koilbatman_1",nil,55],	
			["koilbender_1",nil,55],	
			["koilbender_2",nil,55],	
			["koilclint_1",nil,55],	
			["koileminem_1",nil,55],	
			["koilgraf_1",nil,55],	
			["koilgraf_2",nil,55],	
			["koilgraf_3",nil,55],	
			["koilhulk_1",nil,55],	
			["koiljoker_1",nil,55],	
			["koilpumpkin_1",nil,55],	
			["koilsparta_1",nil,55],	
			["koilsponge_1",nil,55],	
			["koilturtles_1",nil,55],	
			["koilkatie",nil,55],
			["koilpanda",nil,55],
			["koilaiden",nil,55],
			["koileagle",nil,55],
			["koilspecktators",nil,55],
			["koildarth",nil,55],
			["koilgucci",nil,55],
			["koilsmashing",nil,55],
			["koilgoonsquad",nil,55],
			["koilcat",nil,55],
			["koilbp_19",nil,55],	
			["koilbp_21",nil,55],	
			["koilbp_22",nil,55],
			["koilbp_1",nil,55],	
			["koilbp_2",nil,55],	
			["koilbp_3",nil,55],	
			["koilbp_4",nil,55],	
			["koilbp_5",nil,55],	
			["koilbp_6",nil,55],	
			["koilbp_7",nil,55],	
			["koilbp_8",nil,55],	
			["koilbp_9",nil,55],	
			["koilbp_10",nil,55],	
			["koilbp_11",nil,55],	
			["koilbp_12",nil,55],	
			["koilbp_13",nil,55],	
			["koilbp_14",nil,55],	
			["koilbp_15",nil,55],	
			["koilbp_16",nil,55],	
			["koilbp_17",nil,55],	
			["koilbp_18",nil,50],
			["cg_invisbp",nil,50]
		];
	};
};
